/*
 * generated by Xtext
 */
package hsh.swa.ocl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OCLRuntimeModule extends hsh.swa.ocl.AbstractOCLRuntimeModule {

	
}
