/*
 * generated by Xtext
 */
package hsh.swa.ocl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OCLStandaloneSetup extends OCLStandaloneSetupGenerated{

	public static void doSetup() {
		new OCLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

