/**
 * generated by Xtext
 */
package hsh.swa.ocl.validation;

import hsh.swa.ocl.validation.AbstractOCLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OCLValidator extends AbstractOCLValidator {
}
